name: Sync GitHub Issue to Jira

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Create Jira Issue
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: zippie-labs.atlassian.net
          PROJECT_KEY: VEN
          PARENT_KEY: VEN-175
        run: |
          # grab title/body from the GitHub event
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Verify jq is installed
          if ! command -v jq >/dev/null 2>&1; then
            echo "jq is not installed. Please install it."
            exit 1
          fi

          # Build the payload with a single-quoted, multi-line filter
          PAYLOAD=$(jq -n \
            --arg project_key "$PROJECT_KEY" \
            --arg summary     "$ISSUE_TITLE" \
            --arg description "$ISSUE_BODY" \
            --arg parent_key  "$PARENT_KEY" \
            '{
              "fields": {
                "project":     { "key": $project_key },
                "summary":     $summary,
                "description": {
                  "version": 1,
                  "type":    "doc",
                  "content": [
                    {
                      "type": "paragraph",
                      "content": [
                        { "type": "text", "text": $description }
                      ]
                    }
                  ]
                },
                "issuetype": { "name": "Bug" },
                "labels":    ["github"],
                "parent":    { "key": $parent_key }
              }
            }')
          
          echo "Generated Payload:"
          echo "$PAYLOAD"

          # Send the payload to Jira using curl
          curl -D- -u "$JIRA_USER:$JIRA_API_TOKEN" \
            -X POST \
            -H "Content-Type: application/json" \
            --data "$PAYLOAD" \
            "https://$JIRA_DOMAIN/rest/api/3/issue"
